### PR TITLE
add command to list tabs' with the link

### PR DESCRIPTION
**Pull request by k-ueki**
Thanks for the maintenance of chrome-cli. 
Now, there are two types of acquisition of tabs and links respectively, but I had a personal request to acquire tabs and links at once while using chrome-cli. I personally implemented it and used it, but there was the same opinion in the issue, so I submitted a PR.

### CODE REVIEW

**Comment by prasmussen** [comment]
This is great, thank you.
Currently the output doesn't look so good on smaller screens because of the large padding.
What do we think about this output:
```
[1869578131] title: Hacker News, url: https://news.ycombinator.com/
[1869578132] title: Lobsters, url: https://lobste.rs/
```
Ping @tadhg-ohiggins

**Comment by k-ueki** [comment]
Thank you both of you for your comment!

I have changed the output format as you say. I considered using a separator other than `,`, but I thought it would be rare to include it in the title, so I used it. What do you think?

**Comment by tadhg-ohiggins** [comment]
I think it's fine, I can split on `, url: ` if the comma becomes a problem. Thanks again!

**Comment by prasmussen** [comment]
Awesome, thanks for this. I will create a new release later.

**Comment by prasmussen** [comment]
Btw @tadhg-ohiggins, the json output combined with something like `jq` can also be useful if you need a specific output:
```
$ OUTPUT_FORMAT=json chrome-cli list tablinks | jq -r '.tabs[] | "\(.title) => \(.url)"'
Hacker News => https://news.ycombinator.com/
Lobsters => https://lobste.rs/
```

**Pull request merged**
